# I/O
fp_save:                '/home/ubuntu/numbat/experiments/fine-1'
fp_load_dino:           '/home/ubuntu/numbat/experiments/remote-2/remote-2 2021-05-24 08:30:49.pt'
fp_data_msl:            '/home/ubuntu/numbat/data/msl-images'

# Architecture parameterisation
n_classes:              0
in_channels:            3
patch_size:             16
dino_embed_dim:         768

# Training hyperparameters
n_epochs:               64 #300
mixed_precision:        False
# Data loading
data_proportion:        1.0
perform_shuffle:        True
batch_size:             64 #1024
# Schedules
lr_values:              [0.000125, 0.000125, 0.000001] # lr ramped to 0.0005 ∗ batchsize/256 over 10 epochs, adamw opt
lr_epochs:              [0, 6, 64]